# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_expert'),
        ('account', '0006_auto_20160902_1845'),
    ]

    operations = [
    ]
